-- Viole / Flovifly database schema for Supabase.
-- Run this complete file in Supabase Dashboard -> SQL Editor.
-- It is safe to re-run after an earlier version of the schema.

create table if not exists public.viole_users (
  id text primary key,
  username varchar(24) not null unique check (username ~ '^[a-z0-9_]{4,24}$'),
  password_hash text not null,
  display_name varchar(32) not null,
  bio varchar(160) not null default '',
  status varchar(40) not null default 'На связи',
  avatar_color text not null default 'violet',
  is_owner boolean not null default false,
  is_premium boolean not null default false,
  avatar_animated boolean not null default false,
  avatar_url text,
  avatar_path text,
  avatar_is_gif boolean not null default false,
  banner_url text,
  banner_path text,
  banner_is_gif boolean not null default false,
  nick_color varchar(7),
  nick_gradient jsonb,
  nick_animation text not null default 'none',
  created_at timestamptz not null default now()
);

create table if not exists public.viole_chats (
  id text primary key,
  type text not null check (type in ('direct', 'group')),
  name varchar(40),
  avatar_color text,
  owner_id text references public.viole_users(id) on delete set null,
  direct_key text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (type = 'direct' and direct_key is not null)
    or (type = 'group' and direct_key is null)
  )
);

create table if not exists public.viole_chat_members (
  chat_id text not null references public.viole_chats(id) on delete cascade,
  user_id text not null references public.viole_users(id) on delete cascade,
  read_at timestamptz,
  joined_at timestamptz not null default now(),
  primary key (chat_id, user_id)
);

create table if not exists public.viole_messages (
  id text primary key,
  chat_id text not null references public.viole_chats(id) on delete cascade,
  sender_id text not null references public.viole_users(id) on delete cascade,
  text varchar(4000) not null,
  reply_to jsonb,
  reactions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.viole_calls (
  id text primary key,
  chat_id text not null references public.viole_chats(id) on delete cascade,
  participant_ids jsonb not null,
  type text not null check (type in ('audio', 'video')),
  state text not null check (state in ('ringing', 'active', 'rejected', 'ended')),
  started_at timestamptz not null default now(),
  ended_at timestamptz
);

create table if not exists public.viole_sessions (
  id text primary key,
  user_id text not null references public.viole_users(id) on delete cascade,
  token_hash varchar(64) not null unique check (token_hash ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz,
  user_agent_hash varchar(64),
  ip_hash varchar(64),
  check (expires_at > created_at)
);

create table if not exists public.viole_storage_cleanup (
  id bigint generated by default as identity primary key,
  object_path text not null unique,
  attempts integer not null default 0 check (attempts >= 0),
  last_error varchar(500) not null default '',
  created_at timestamptz not null default now(),
  next_attempt_at timestamptz not null default now()
);

create index if not exists viole_chat_members_user_id_idx
  on public.viole_chat_members(user_id, chat_id);
create index if not exists viole_messages_chat_created_idx
  on public.viole_messages(chat_id, created_at desc);
create index if not exists viole_messages_sender_idx
  on public.viole_messages(sender_id);
create index if not exists viole_chats_updated_idx
  on public.viole_chats(updated_at desc);
create index if not exists viole_sessions_user_idx
  on public.viole_sessions(user_id, expires_at desc);
create index if not exists viole_sessions_expiry_idx
  on public.viole_sessions(expires_at);
create index if not exists viole_storage_cleanup_due_idx
  on public.viole_storage_cleanup(next_attempt_at);

alter table public.viole_users enable row level security;
alter table public.viole_chats enable row level security;
alter table public.viole_chat_members enable row level security;
alter table public.viole_messages enable row level security;
alter table public.viole_calls enable row level security;
alter table public.viole_sessions enable row level security;
alter table public.viole_storage_cleanup enable row level security;

-- The browser never talks to these tables directly. Only the Node.js backend uses
-- SUPABASE_SECRET_KEY / SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS.
revoke all on table public.viole_users from anon, authenticated;
revoke all on table public.viole_chats from anon, authenticated;
revoke all on table public.viole_chat_members from anon, authenticated;
revoke all on table public.viole_messages from anon, authenticated;
revoke all on table public.viole_calls from anon, authenticated;
revoke all on table public.viole_sessions from anon, authenticated;
revoke all on table public.viole_storage_cleanup from anon, authenticated;

revoke all on sequence public.viole_storage_cleanup_id_seq from anon, authenticated;

grant all on table public.viole_users to service_role;
grant all on table public.viole_chats to service_role;
grant all on table public.viole_chat_members to service_role;
grant all on table public.viole_messages to service_role;
grant all on table public.viole_calls to service_role;
grant all on table public.viole_sessions to service_role;
grant all on table public.viole_storage_cleanup to service_role;
grant all on sequence public.viole_storage_cleanup_id_seq to service_role;

create or replace function public.viole_list_chats(p_user_id text)
returns table (
  id text,
  type text,
  name text,
  avatar_color text,
  owner_id text,
  created_at timestamptz,
  updated_at timestamptz,
  member_ids text[],
  read_at jsonb,
  last_message jsonb,
  unread_count bigint
)
language sql
security definer
set search_path = public
stable
as $$
  select
    c.id,
    c.type,
    c.name,
    c.avatar_color,
    c.owner_id,
    c.created_at,
    c.updated_at,
    (
      select coalesce(array_agg(cm.user_id order by cm.user_id), array[]::text[])
      from public.viole_chat_members cm
      where cm.chat_id = c.id
    ) as member_ids,
    case
      when mine.read_at is null then '{}'::jsonb
      else jsonb_build_object(p_user_id, mine.read_at)
    end as read_at,
    (
      select to_jsonb(m)
      from public.viole_messages m
      where m.chat_id = c.id
        and (c.type <> 'group' or m.created_at >= mine.joined_at)
      order by m.created_at desc
      limit 1
    ) as last_message,
    (
      select count(*)
      from public.viole_messages m
      where m.chat_id = c.id
        and m.sender_id <> p_user_id
        and (c.type <> 'group' or m.created_at >= mine.joined_at)
        and (mine.read_at is null or m.created_at > mine.read_at)
    ) as unread_count
  from public.viole_chat_members mine
  join public.viole_chats c on c.id = mine.chat_id
  where mine.user_id = p_user_id
  order by c.updated_at desc;
$$;

create or replace function public.viole_create_direct_chat(
  p_chat_id text,
  p_user_a text,
  p_user_b text,
  p_created_at timestamptz
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_key text;
  v_chat_id text;
begin
  if p_user_a = p_user_b then
    raise exception 'A direct chat requires two different users';
  end if;

  v_key := least(p_user_a, p_user_b) || ':' || greatest(p_user_a, p_user_b);

  insert into public.viole_chats (id, type, direct_key, created_at, updated_at)
  values (p_chat_id, 'direct', v_key, p_created_at, p_created_at)
  on conflict (direct_key) do update set direct_key = excluded.direct_key
  returning id into v_chat_id;

  insert into public.viole_chat_members (chat_id, user_id, joined_at)
  values (v_chat_id, p_user_a, p_created_at), (v_chat_id, p_user_b, p_created_at)
  on conflict (chat_id, user_id) do nothing;

  return v_chat_id;
end;
$$;

create or replace function public.viole_create_group_chat(
  p_chat_id text,
  p_owner_id text,
  p_name text,
  p_avatar_color text,
  p_member_ids text[],
  p_created_at timestamptz
)
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  if cardinality(coalesce(p_member_ids, array[]::text[])) > 49 then
    raise exception 'A group cannot contain more than 50 members';
  end if;

  insert into public.viole_chats (
    id, type, name, avatar_color, owner_id, created_at, updated_at
  ) values (
    p_chat_id, 'group', p_name, p_avatar_color, p_owner_id, p_created_at, p_created_at
  );

  insert into public.viole_chat_members (chat_id, user_id, joined_at)
  select p_chat_id, member_id, p_created_at
  from (
    select distinct unnest(coalesce(p_member_ids, array[]::text[]) || array[p_owner_id]) as member_id
  ) members;

  return p_chat_id;
end;
$$;

revoke all on function public.viole_list_chats(text) from public, anon, authenticated;
revoke all on function public.viole_create_direct_chat(text, text, text, timestamptz) from public, anon, authenticated;
revoke all on function public.viole_create_group_chat(text, text, text, text, text[], timestamptz) from public, anon, authenticated;

grant execute on function public.viole_list_chats(text) to service_role;
grant execute on function public.viole_create_direct_chat(text, text, text, timestamptz) to service_role;
grant execute on function public.viole_create_group_chat(text, text, text, text, text[], timestamptz) to service_role;

-- Public profile-media bucket: files can be viewed by URL. Uploads and deletes are
-- performed only by the trusted Node.js backend with the secret/service-role key.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'profile-media',
  'profile-media',
  true,
  8388608,
  array['image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
