const fs0=require('fs'),path0=require('path');try{for(const line of fs0.readFileSync(path0.join(__dirname,'.env'),'utf8').split(/\r?\n/)){const m=line.match(/^([A-Z0-9_]+)=(.*)$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2]}}catch{}
const express=require('express'),http=require('http'),{Server}=require('socket.io'),crypto=require('crypto'),fs=require('fs'),path=require('path');
const app=express(),server=http.createServer(app),io=new Server(server,{maxHttpBufferSize:8e6});
const PORT=Number(process.env.PORT||3000),SECRET=process.env.JWT_SECRET||'development-only-change-me',DB_FILE=path.join(__dirname,'data','db.json');
const fresh={users:[],chats:[],messages:[],calls:[]};let db=load(),writeChain=Promise.resolve();
function load(){try{return {...structuredClone(fresh),...JSON.parse(fs.readFileSync(DB_FILE,'utf8'))}}catch{return structuredClone(fresh)}}
function save(){const body=JSON.stringify(db,null,2),tmp=DB_FILE+'.tmp';writeChain=writeChain.then(async()=>{await fs.promises.mkdir(path.dirname(DB_FILE),{recursive:true});await fs.promises.writeFile(tmp,body);await fs.promises.rename(tmp,DB_FILE)});return writeChain}
const id=p=>p+'_'+crypto.randomBytes(9).toString('base64url'),now=()=>new Date().toISOString();
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return new Promise((ok,no)=>crypto.scrypt(password,salt,64,(e,key)=>e?no(e):ok(salt+':'+key.toString('hex'))))}
async function verifyPassword(password,stored){const salt=stored.split(':')[0],value=await hashPassword(password,salt);return value.length===stored.length&&crypto.timingSafeEqual(Buffer.from(value),Buffer.from(stored))}
function sign(uid){const p=Buffer.from(JSON.stringify({sub:uid,exp:Date.now()+2592e6})).toString('base64url'),s=crypto.createHmac('sha256',SECRET).update(p).digest('base64url');return p+'.'+s}
function verify(token=''){try{const [p,s]=token.split('.'),e=crypto.createHmac('sha256',SECRET).update(p).digest('base64url');if(!s||s.length!==e.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e)))return null;const x=JSON.parse(Buffer.from(p,'base64url'));return x.exp>Date.now()?x.sub:null}catch{return null}}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(v=>v.trim().split(/=(.*)/s).slice(0,2).map(decodeURIComponent)))}
function auth(req,res,next){const u=db.users.find(x=>x.id===verify(cookies(req).viole_session));if(!u)return res.status(401).json({error:'AUTH_REQUIRED'});req.user=u;next()}
function pub(u){return u&&{id:u.id,username:u.username,display_name:u.display_name||u.username,bio:u.bio||'',avatar:u.avatar||'',avatar_color:u.avatar_color,premium:true,created_at:u.created_at}}
function member(c,uid){return c&&c.member_ids.includes(uid)}
function cookie(res,t){res.setHeader('Set-Cookie',`viole_session=${t}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000${process.env.NODE_ENV==='production'?'; Secure':''}`)}
function viewChat(c,uid){const last=db.messages.filter(m=>m.chat_id===c.id&&!m.deleted).at(-1),other=c.type==='direct'?pub(db.users.find(u=>c.member_ids.includes(u.id)&&u.id!==uid)):null;return {...c,other,last_message:last||null,unread:db.messages.filter(m=>m.chat_id===c.id&&m.sender_id!==uid&&!m.read_by?.includes(uid)).length}}
app.disable('x-powered-by');app.use(express.json({limit:'6mb'}));app.use(express.static(path.join(__dirname,'public'),{extensions:['html']}));
app.get('/api/health',(q,r)=>r.json({ok:true,service:'viole'}));
app.get('/api/config',(q,r)=>{const iceServers=[{urls:(process.env.STUN_URLS||'stun:stun.l.google.com:19302').split(',')}];if(process.env.TURN_URL)iceServers.push({urls:process.env.TURN_URL,username:process.env.TURN_USERNAME,credential:process.env.TURN_CREDENTIAL});r.json({iceServers})});
app.post('/api/auth/register',async(q,r)=>{try{const username=String(q.body.username||'').toLowerCase().trim(),password=String(q.body.password||'');if(!/^[a-z0-9_]{4,24}$/.test(username))return r.status(400).json({error:'INVALID_USERNAME'});if(password.length<8||password.length>128)return r.status(400).json({error:'INVALID_PASSWORD'});if(db.users.some(u=>u.username===username))return r.status(409).json({error:'USERNAME_TAKEN'});const user={id:id('usr'),username,display_name:username,bio:'',avatar:'',avatar_color:['violet','rose','blue','green'][db.users.length%4],premium:true,password_hash:await hashPassword(password),created_at:now()};db.users.push(user);const saved={id:id('chat'),type:'saved',title:'Избранное',owner_id:user.id,member_ids:[user.id],created_at:now(),updated_at:now(),pinned_by:[user.id]};db.chats.push(saved);await save();cookie(r,sign(user.id));r.status(201).json({user:pub(user)})}catch(e){r.status(500).json({error:'SERVER_ERROR'})}});
app.post('/api/auth/login',async(q,r)=>{const u=db.users.find(x=>x.username===String(q.body.username||'').toLowerCase().trim());if(!u||!await verifyPassword(String(q.body.password||''),u.password_hash))return r.status(401).json({error:'BAD_CREDENTIALS'});cookie(r,sign(u.id));r.json({user:pub(u)})});
app.post('/api/auth/logout',(q,r)=>{r.setHeader('Set-Cookie','viole_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');r.json({ok:true})});
app.get('/api/me',auth,(q,r)=>r.json({user:pub(q.user)}));
app.patch('/api/me',auth,async(q,r)=>{const name=String(q.body.display_name||'').trim().slice(0,40),bio=String(q.body.bio||'').trim().slice(0,160),avatar=String(q.body.avatar||'');if(name)q.user.display_name=name;q.user.bio=bio;if(/^data:image\/(png|jpeg|webp);base64,/.test(avatar)&&avatar.length<1.5e6)q.user.avatar=avatar;await save();r.json({user:pub(q.user)})});
app.get('/api/users',auth,(q,r)=>{const s=String(q.query.q||'').toLowerCase().replace('@','').slice(0,30);r.json({users:db.users.filter(u=>u.id!==q.user.id&&(u.username.includes(s)||(u.display_name||'').toLowerCase().includes(s))).slice(0,30).map(pub)})});
app.get('/api/chats',auth,(q,r)=>r.json({chats:db.chats.filter(c=>member(c,q.user.id)).map(c=>viewChat(c,q.user.id)).sort((a,b)=>Number((b.pinned_by||[]).includes(q.user.id))-Number((a.pinned_by||[]).includes(q.user.id))||String(b.updated_at).localeCompare(String(a.updated_at)))}));
app.post('/api/chats/direct',auth,async(q,r)=>{const other=db.users.find(u=>u.id===q.body.user_id);if(!other||other.id===q.user.id)return r.status(400).json({error:'INVALID_USER'});let c=db.chats.find(c=>c.type==='direct'&&c.member_ids.includes(q.user.id)&&c.member_ids.includes(other.id));if(!c){c={id:id('chat'),type:'direct',member_ids:[q.user.id,other.id],created_at:now(),updated_at:now(),pinned_by:[],muted_by:[]};db.chats.push(c);await save()}r.json({chat:viewChat(c,q.user.id)})});
app.post('/api/chats',auth,async(q,r)=>{const type=q.body.type==='channel'?'channel':'group',title=String(q.body.title||'').trim().slice(0,60);if(title.length<2)return r.status(400).json({error:'INVALID_TITLE'});const ids=[q.user.id,...(q.body.member_ids||[]).filter(x=>db.users.some(u=>u.id===x&&u.id!==q.user.id))];const c={id:id('chat'),type,title,description:String(q.body.description||'').slice(0,180),owner_id:q.user.id,admin_ids:[q.user.id],member_ids:[...new Set(ids)],created_at:now(),updated_at:now(),pinned_by:[],muted_by:[]};db.chats.push(c);await save();for(const sid of c.member_ids.flatMap(uid=>[...(sockets.get(uid)||[])]))io.to(sid).emit('chat:new',viewChat(c,uidForSocket(sid)));r.status(201).json({chat:viewChat(c,q.user.id)})});
app.patch('/api/chats/:id',auth,async(q,r)=>{const c=db.chats.find(x=>x.id===q.params.id);if(!member(c,q.user.id))return r.status(403).json({error:'FORBIDDEN'});for(const [key,list] of [['pin','pinned_by'],['mute','muted_by']])if(typeof q.body[key]==='boolean'){c[list]=c[list]||[];c[list]=q.body[key]?[...new Set([...c[list],q.user.id])]:c[list].filter(x=>x!==q.user.id)}if(c.owner_id===q.user.id&&q.body.title)c.title=String(q.body.title).slice(0,60);await save();r.json({chat:viewChat(c,q.user.id)})});
app.get('/api/chats/:id/messages',auth,(q,r)=>{const c=db.chats.find(x=>x.id===q.params.id);if(!member(c,q.user.id))return r.status(403).json({error:'FORBIDDEN'});const term=String(q.query.q||'').toLowerCase();let ms=db.messages.filter(m=>m.chat_id===c.id);if(term)ms=ms.filter(m=>(m.text||'').toLowerCase().includes(term));r.json({messages:ms.slice(-500).map(m=>({...m,sender:pub(db.users.find(u=>u.id===m.sender_id)),reply:db.messages.find(x=>x.id===m.reply_to)}))})});
app.post('/api/chats/:id/read',auth,async(q,r)=>{const c=db.chats.find(x=>x.id===q.params.id);if(!member(c,q.user.id))return r.status(403).json({error:'FORBIDDEN'});for(const m of db.messages.filter(m=>m.chat_id===c.id)){m.read_by=m.read_by||[];if(!m.read_by.includes(q.user.id))m.read_by.push(q.user.id)}await save();io.to(c.id).emit('message:read',{chat_id:c.id,user_id:q.user.id});r.json({ok:true})});
app.get('/api/search',auth,(q,r)=>{const term=String(q.query.q||'').toLowerCase().trim();if(term.length<2)return r.json({messages:[]});r.json({messages:db.messages.filter(m=>!m.deleted&&(m.text||'').toLowerCase().includes(term)&&member(db.chats.find(c=>c.id===m.chat_id),q.user.id)).slice(-50).reverse()})});
const sockets=new Map();function online(uid){return !!sockets.get(uid)?.size}function uidForSocket(sid){for(const [uid,set] of sockets)if(set.has(sid))return uid;return null}function presence(uid){io.emit('presence',{user_id:uid,online:online(uid)})}
io.use((s,next)=>{const u=db.users.find(x=>x.id===verify(cookies(s.request).viole_session));if(!u)return next(new Error('unauthorized'));s.user=u;next()});
io.on('connection',s=>{const uid=s.user.id;if(!sockets.has(uid))sockets.set(uid,new Set());sockets.get(uid).add(s.id);presence(uid);db.chats.filter(c=>member(c,uid)).forEach(c=>s.join(c.id));s.on('presence:query',(ids,ack)=>ack?.(Object.fromEntries((ids||[]).map(x=>[x,online(x)]))));
 s.on('message:send',async(data,ack)=>{const c=db.chats.find(x=>x.id===data.chat_id),text=String(data.text||'').trim().slice(0,4000),a=data.attachment;if(!member(c,uid)||(!text&&!a))return ack?.({error:'INVALID_MESSAGE'});if(c.type==='channel'&&c.owner_id!==uid&&!c.admin_ids?.includes(uid))return ack?.({error:'ADMINS_ONLY'});let attachment=null;if(a&&/^data:(image\/(png|jpeg|webp|gif)|audio\/(webm|ogg)|application\/pdf);base64,/.test(a.data||'')&&(a.data||'').length<5.5e6)attachment={name:String(a.name||'file').slice(0,100),mime:String(a.mime||''),data:a.data,size:Number(a.size||0)};const m={id:id('msg'),chat_id:c.id,sender_id:uid,type:attachment?.mime.startsWith('audio/')?'voice':attachment?'file':'text',text,attachment,reply_to:data.reply_to||null,reactions:{},read_by:[uid],created_at:now()};db.messages.push(m);c.updated_at=m.created_at;await save();const out={...m,sender:pub(s.user),reply:db.messages.find(x=>x.id===m.reply_to)};io.to(c.id).emit('message:new',out);ack?.({ok:true,message:out})});
 s.on('message:edit',async(data,ack)=>{const m=db.messages.find(x=>x.id===data.id),text=String(data.text||'').trim().slice(0,4000);if(!m||m.sender_id!==uid||!text)return ack?.({error:'FORBIDDEN'});m.text=text;m.edited_at=now();await save();io.to(m.chat_id).emit('message:update',m);ack?.({ok:true})});
 s.on('message:delete',async(data,ack)=>{const m=db.messages.find(x=>x.id===data.id);if(!m||m.sender_id!==uid)return ack?.({error:'FORBIDDEN'});m.deleted=true;m.text='';m.attachment=null;await save();io.to(m.chat_id).emit('message:update',m);ack?.({ok:true})});
 s.on('message:react',async data=>{const m=db.messages.find(x=>x.id===data.id),emoji=['❤','👍','🔥','😂','😮','😢'].includes(data.emoji)?data.emoji:'❤';if(!m||!member(db.chats.find(c=>c.id===m.chat_id),uid))return;m.reactions=m.reactions||{};for(const e of Object.keys(m.reactions))m.reactions[e]=m.reactions[e].filter(x=>x!==uid);m.reactions[emoji]=[...new Set([...(m.reactions[emoji]||[]),uid])];await save();io.to(m.chat_id).emit('message:update',m)});
 s.on('typing',d=>{const c=db.chats.find(x=>x.id===d.chat_id);if(member(c,uid))s.to(c.id).emit('typing',{chat_id:c.id,user_id:uid,active:!!d.active})});
 s.on('call:start',async(d,ack)=>{const c=db.chats.find(x=>x.id===d.chat_id);if(!member(c,uid)||c.type!=='direct')return ack?.({error:'FORBIDDEN'});const target=c.member_ids.find(x=>x!==uid),call={id:id('call'),chat_id:c.id,initiator_id:uid,participant_ids:c.member_ids,type:d.type==='video'?'video':'audio',state:'ringing',started_at:now()};db.calls.push(call);await save();for(const sid of sockets.get(target)||[])io.to(sid).emit('call:incoming',{call,from:pub(s.user)});ack?.({ok:true,call})});
 for(const ev of ['call:accept','call:reject','call:end'])s.on(ev,async d=>{const call=db.calls.find(c=>c.id===d.call_id&&c.participant_ids.includes(uid));if(!call)return;call.state=ev==='call:accept'?'active':ev==='call:reject'?'rejected':'ended';if(call.state!=='active')call.ended_at=now();await save();const target=call.participant_ids.find(x=>x!==uid);for(const sid of sockets.get(target)||[])io.to(sid).emit(ev==='call:accept'?'call:accepted':ev,{call_id:call.id})});
 s.on('call:signal',d=>{const call=db.calls.find(c=>c.id===d.call_id&&c.participant_ids.includes(uid));if(!call)return;const target=call.participant_ids.find(x=>x!==uid);for(const sid of sockets.get(target)||[])io.to(sid).emit('call:signal',{call_id:call.id,signal:d.signal})});
 s.on('disconnect',()=>{sockets.get(uid)?.delete(s.id);if(!sockets.get(uid)?.size)sockets.delete(uid);presence(uid)})});
app.get('*',(q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));server.listen(PORT,()=>console.log(`Viole: http://localhost:${PORT}`));
