const fs0=require('fs'),path0=require('path');try{for(const l of fs0.readFileSync(path0.join(__dirname,'.env'),'utf8').split(/\r?\n/)){const m=l.match(/^([A-Z0-9_]+)=(.*)$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2]}}catch{}
const express=require('express'),http=require('http'),{Server}=require('socket.io'),crypto=require('crypto'),fs=require('fs'),path=require('path');
const app=express(),server=http.createServer(app),io=new Server(server,{maxHttpBufferSize:6e6});
const PORT=+(process.env.PORT||3000),SECRET=process.env.JWT_SECRET||'dev-change-me',FILE=path.join(__dirname,'data','db.json');
const blank={users:[],chats:[],messages:[],calls:[]};let db=load(),writes=Promise.resolve();
function load(){try{return {...structuredClone(blank),...JSON.parse(fs.readFileSync(FILE,'utf8'))}}catch{return structuredClone(blank)}}
function save(){const body=JSON.stringify(db,null,2),tmp=FILE+'.tmp';writes=writes.then(async()=>{await fs.promises.mkdir(path.dirname(FILE),{recursive:true});await fs.promises.writeFile(tmp,body);await fs.promises.rename(tmp,FILE)});return writes}
const id=p=>p+'_'+crypto.randomBytes(9).toString('base64url'),now=()=>new Date().toISOString();
function hash(p,s=crypto.randomBytes(16).toString('hex')){return new Promise((ok,no)=>crypto.scrypt(p,s,64,(e,k)=>e?no(e):ok(s+':'+k.toString('hex'))))}
async function verifyPass(p,v){try{const [s]=v.split(':'),a=Buffer.from(await hash(p,s)),b=Buffer.from(v);return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}}
function sign(uid){const p=Buffer.from(JSON.stringify({sub:uid,exp:Date.now()+2592e6})).toString('base64url'),s=crypto.createHmac('sha256',SECRET).update(p).digest('base64url');return p+'.'+s}
function verify(t=''){try{const [p,s]=t.split('.'),a=Buffer.from(s||''),b=Buffer.from(crypto.createHmac('sha256',SECRET).update(p).digest('base64url'));if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return null;const x=JSON.parse(Buffer.from(p,'base64url'));return x.exp>Date.now()?x.sub:null}catch{return null}}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>x.trim().split(/=(.*)/s).slice(0,2).map(decodeURIComponent)))}
const pub=u=>u&&({id:u.id,username:u.username,display_name:u.display_name||u.username,avatar_color:u.avatar_color,created_at:u.created_at,bio:u.bio||'',profile_style:u.profile_style||'violet'});
function auth(q,r,n){const u=db.users.find(x=>x.id===verify(cookies(q).viole_session));if(!u)return r.status(401).json({error:'AUTH_REQUIRED'});q.user=u;n()}
const member=(c,u)=>c&&c.member_ids.includes(u),admin=(c,u)=>c&&c.admin_ids?.includes(u);
function setCookie(r,t,max=2592000){r.setHeader('Set-Cookie',`viole_session=${t}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${max}${process.env.NODE_ENV==='production'?'; Secure':''}`)}
const attempts=new Map();function limited(ip){const t=Date.now(),a=(attempts.get(ip)||[]).filter(x=>t-x<60000);a.push(t);attempts.set(ip,a);return a.length>20}
app.disable('x-powered-by');app.use(express.json({limit:'6mb'}));app.use(express.static(path.join(__dirname,'public')));
app.get('/api/health',(q,r)=>r.json({ok:true,service:'viole'}));
app.get('/api/config',(q,r)=>{const iceServers=[{urls:(process.env.STUN_URLS||'stun:stun.l.google.com:19302').split(',')}];if(process.env.TURN_URL)iceServers.push({urls:process.env.TURN_URL,username:process.env.TURN_USERNAME,credential:process.env.TURN_CREDENTIAL});r.json({iceServers})});
app.post('/api/auth/register',async(q,r)=>{try{if(limited(q.ip))return r.status(429).json({error:'RATE_LIMIT'});const username=String(q.body.username||'').toLowerCase().trim(),password=String(q.body.password||'');if(!/^[a-z0-9_]{4,24}$/.test(username))return r.status(400).json({error:'INVALID_USERNAME'});if(password.length<8||password.length>128)return r.status(400).json({error:'INVALID_PASSWORD'});if(db.users.some(x=>x.username===username))return r.status(409).json({error:'USERNAME_TAKEN'});const u={id:id('usr'),username,display_name:username,avatar_color:['violet','plum','blue','rose'][db.users.length%4],password_hash:await hash(password),created_at:now()};db.users.push(u);await save();setCookie(r,sign(u.id));r.status(201).json({user:pub(u)})}catch{r.status(500).json({error:'SERVER_ERROR'})}});
app.post('/api/auth/login',async(q,r)=>{if(limited(q.ip))return r.status(429).json({error:'RATE_LIMIT'});const u=db.users.find(x=>x.username===String(q.body.username||'').toLowerCase().trim());if(!u||!await verifyPass(String(q.body.password||''),u.password_hash))return r.status(401).json({error:'BAD_CREDENTIALS'});setCookie(r,sign(u.id));r.json({user:pub(u)})});
app.patch('/api/profile',auth,async(q,r)=>{const name=String(q.body.display_name||'').trim().slice(0,40),bio=String(q.body.bio||'').trim().slice(0,140),style=['violet','aurora','mono','sunset'].includes(q.body.profile_style)?q.body.profile_style:'violet';q.user.display_name=name||q.user.username;q.user.bio=bio;q.user.profile_style=style;await save();r.json({user:pub(q.user)})});
app.post('/api/auth/logout',(q,r)=>{setCookie(r,'',0);r.json({ok:true})});app.get('/api/me',auth,(q,r)=>r.json({user:pub(q.user)}));
app.get('/api/users',auth,(q,r)=>{const s=String(q.query.q||'').toLowerCase().replace('@','').slice(0,24);r.json({users:s?db.users.filter(x=>x.id!==q.user.id&&x.username.includes(s)).slice(0,20).map(pub):[]})});
function viewChat(c,uid){const last=db.messages.filter(m=>m.chat_id===c.id&&!m.deleted_at).at(-1);return {...c,members:c.member_ids.map(x=>pub(db.users.find(u=>u.id===x))).filter(Boolean),other:pub(db.users.find(u=>u.id!==uid&&c.member_ids.includes(u.id))),last_message:last||null,pinned:(c.pinned_ids||[]).map(x=>db.messages.find(m=>m.id===x)).filter(Boolean)}}
app.get('/api/chats',auth,(q,r)=>r.json({chats:db.chats.filter(c=>member(c,q.user.id)).map(c=>viewChat(c,q.user.id)).sort((a,b)=>String(b.updated_at).localeCompare(String(a.updated_at)))}));
app.post('/api/chats',auth,async(q,r)=>{const type=['group','channel'].includes(q.body.type)?q.body.type:'direct',ids=[...new Set([q.user.id,...(q.body.member_ids||[])])].filter(x=>db.users.some(u=>u.id===x));if(type==='direct'&&ids.length!==2)return r.status(400).json({error:'INVALID_MEMBERS'});if(type!=='direct'&&(ids.length<2||!String(q.body.title||'').trim()))return r.status(400).json({error:'INVALID_CHAT'});let c=type==='direct'?db.chats.find(x=>x.type==='direct'&&x.member_ids.length===2&&ids.every(y=>x.member_ids.includes(y))):null;if(!c){c={id:id('chat'),type,title:type==='direct'?'':String(q.body.title).trim().slice(0,60),member_ids:ids,admin_ids:[q.user.id],pinned_ids:[],created_at:now(),updated_at:now()};db.chats.push(c);await save()}r.json({chat:viewChat(c,q.user.id)})});
app.get('/api/chats/:id/messages',auth,(q,r)=>{const c=db.chats.find(x=>x.id===q.params.id);if(!member(c,q.user.id))return r.status(403).json({error:'FORBIDDEN'});const term=String(q.query.q||'').toLowerCase();let m=db.messages.filter(x=>x.chat_id===c.id);if(term)m=m.filter(x=>String(x.text||'').toLowerCase().includes(term)||String(x.file?.name||'').toLowerCase().includes(term));r.json({messages:m.slice(-300)})});
app.patch('/api/messages/:id',auth,async(q,r)=>{const m=db.messages.find(x=>x.id===q.params.id),c=db.chats.find(x=>x.id===m?.chat_id);if(!m||m.sender_id!==q.user.id||!member(c,q.user.id)||m.deleted_at)return r.status(403).json({error:'FORBIDDEN'});const text=String(q.body.text||'').trim().slice(0,4000);if(!text)return r.status(400).json({error:'INVALID_MESSAGE'});m.text=text;m.edited_at=now();await save();io.to(c.id).emit('message:update',m);r.json({message:m})});
app.delete('/api/messages/:id',auth,async(q,r)=>{const m=db.messages.find(x=>x.id===q.params.id),c=db.chats.find(x=>x.id===m?.chat_id);if(!m||!member(c,q.user.id)||(m.sender_id!==q.user.id&&!admin(c,q.user.id)))return r.status(403).json({error:'FORBIDDEN'});m.text='';m.file=null;m.deleted_at=now();await save();io.to(c.id).emit('message:update',m);r.json({ok:true})});
const sockets=new Map();const online=u=>sockets.get(u)?.size>0;function emitPresence(u){io.emit('presence',{user_id:u,online:online(u)})}
io.use((s,n)=>{const u=db.users.find(x=>x.id===verify(cookies(s.request).viole_session));if(!u)return n(new Error('unauthorized'));s.user=u;n()});
io.on('connection',s=>{const uid=s.user.id;if(!sockets.has(uid))sockets.set(uid,new Set());sockets.get(uid).add(s.id);db.chats.filter(c=>member(c,uid)).forEach(c=>s.join(c.id));emitPresence(uid);
s.on('presence:query',(ids,ack)=>ack?.(Object.fromEntries((ids||[]).map(x=>[x,online(x)]))));
s.on('typing',d=>{const c=db.chats.find(x=>x.id===d.chat_id);if(member(c,uid))s.to(c.id).emit('typing',{chat_id:c.id,user_id:uid,active:!!d.active})});
s.on('message:send',async(d,ack)=>{const c=db.chats.find(x=>x.id===d.chat_id),text=String(d.text||'').trim().slice(0,4000),file=d.file&&typeof d.file.data==='string'&&d.file.data.length<5.5e6?{name:String(d.file.name||'file').slice(0,100),type:String(d.file.type||'application/octet-stream').slice(0,80),data:d.file.data}:null;if(!member(c,uid)||(!text&&!file)||c.type==='channel'&&!admin(c,uid))return ack?.({error:'INVALID_MESSAGE'});const reply=db.messages.find(x=>x.id===d.reply_to&&x.chat_id===c.id);const m={id:id('msg'),chat_id:c.id,sender_id:uid,type:file?'file':'text',text,file,reply_to:reply?.id||null,reactions:{},created_at:now()};db.messages.push(m);c.updated_at=m.created_at;await save();io.to(c.id).emit('message:new',m);ack?.({ok:true,message:m})});
s.on('message:react',async(d)=>{const m=db.messages.find(x=>x.id===d.message_id),c=db.chats.find(x=>x.id===m?.chat_id),emoji=['💜','👍','🔥','😂','😮'].includes(d.emoji)?d.emoji:'💜';if(!m||!member(c,uid))return;m.reactions||={};for(const e of Object.keys(m.reactions))m.reactions[e]=m.reactions[e].filter(x=>x!==uid);m.reactions[emoji]=[...new Set([...(m.reactions[emoji]||[]),uid])];await save();io.to(c.id).emit('message:update',m)});
s.on('message:pin',async(d)=>{const m=db.messages.find(x=>x.id===d.message_id),c=db.chats.find(x=>x.id===m?.chat_id);if(!m||!member(c,uid))return;c.pinned_ids=c.pinned_ids||[];c.pinned_ids=c.pinned_ids.includes(m.id)?c.pinned_ids.filter(x=>x!==m.id):[m.id,...c.pinned_ids].slice(0,5);await save();io.to(c.id).emit('chat:update',viewChat(c,uid))});
s.on('call:start',async(d,ack)=>{const c=db.chats.find(x=>x.id===d.chat_id);if(!member(c,uid)||c.type!=='direct')return ack?.({error:'FORBIDDEN'});const target=c.member_ids.find(x=>x!==uid);if(!online(target))return ack?.({error:'OFFLINE'});if(db.calls.some(x=>x.state==='ringing'&&x.participant_ids.includes(target)))return ack?.({error:'BUSY'});const call={id:id('call'),chat_id:c.id,initiator_id:uid,participant_ids:c.member_ids,type:d.type==='video'?'video':'audio',state:'ringing',started_at:now()};db.calls.push(call);await save();for(const sid of sockets.get(target)||[])io.to(sid).emit('call:incoming',{call,from:pub(s.user)});ack?.({call})});
for(const ev of ['call:accept','call:reject','call:end'])s.on(ev,async d=>{const call=db.calls.find(x=>x.id===d.call_id&&x.participant_ids.includes(uid));if(!call)return;call.state=ev.split(':')[1];if(ev!=='call:accept')call.ended_at=now();await save();const target=call.participant_ids.find(x=>x!==uid);for(const sid of sockets.get(target)||[])io.to(sid).emit(ev==='call:accept'?'call:accepted':ev,{call_id:call.id})});
s.on('call:signal',d=>{const c=db.calls.find(x=>x.id===d.call_id&&x.participant_ids.includes(uid));if(!c)return;for(const sid of sockets.get(c.participant_ids.find(x=>x!==uid))||[])io.to(sid).emit('call:signal',{call_id:c.id,signal:d.signal})});
s.on('disconnect',()=>{sockets.get(uid)?.delete(s.id);if(!sockets.get(uid)?.size)sockets.delete(uid);emitPresence(uid)})});
app.get('*',(q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));server.listen(PORT,()=>console.log(`Viole: http://localhost:${PORT}`));
