const fs=require('fs'),path=require('path'),crypto=require('crypto'),express=require('express'),http=require('http');
try{for(const line of fs.readFileSync(path.join(__dirname,'.env'),'utf8').split(/\r?\n/)){const m=line.match(/^([A-Z0-9_]+)=(.*)$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2]}}catch{}
const {Server}=require('socket.io');
const app=express(),server=http.createServer(app),io=new Server(server,{maxHttpBufferSize:1e6});
const PORT=Number(process.env.PORT||3000),SECRET=process.env.JWT_SECRET||'development-only-change-me',DB_FILE=path.join(__dirname,'data','db.json');
const blank={users:[],chats:[],messages:[],calls:[]};let db=load(),writeChain=Promise.resolve();
function load(){try{return {...structuredClone(blank),...JSON.parse(fs.readFileSync(DB_FILE,'utf8'))}}catch{return structuredClone(blank)}}
function save(){const body=JSON.stringify(db,null,2),tmp=DB_FILE+'.tmp';writeChain=writeChain.then(async()=>{await fs.promises.mkdir(path.dirname(DB_FILE),{recursive:true});await fs.promises.writeFile(tmp,body);await fs.promises.rename(tmp,DB_FILE)});return writeChain}
const id=p=>p+'_'+crypto.randomBytes(9).toString('base64url');
const hashPassword=(password,salt=crypto.randomBytes(16).toString('hex'))=>new Promise((ok,no)=>crypto.scrypt(password,salt,64,(e,key)=>e?no(e):ok(salt+':'+key.toString('hex'))));
async function verifyPassword(password,stored){try{const [salt]=stored.split(':'),value=await hashPassword(password,salt),a=Buffer.from(value),b=Buffer.from(stored);return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}}
function sign(uid){const p=Buffer.from(JSON.stringify({sub:uid,exp:Date.now()+2592e6})).toString('base64url'),s=crypto.createHmac('sha256',SECRET).update(p).digest('base64url');return p+'.'+s}
function verify(token=''){try{const [p,s]=token.split('.'),a=Buffer.from(s||''),b=Buffer.from(crypto.createHmac('sha256',SECRET).update(p||'').digest('base64url'));if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return null;const x=JSON.parse(Buffer.from(p,'base64url'));return x.exp>Date.now()?x.sub:null}catch{return null}}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(v=>v.trim().split(/=(.*)/s).slice(0,2).map(decodeURIComponent)))}
function auth(req,res,next){const uid=verify(cookies(req).viole_session);const user=db.users.find(x=>x.id===uid);if(!user)return res.status(401).json({error:'AUTH_REQUIRED'});req.user=user;next()}
const publicUser=u=>({id:u.id,username:u.username,display_name:u.display_name||u.username,bio:u.bio||'',status:u.status||'На связи',avatar_color:u.avatar_color,is_owner:!!u.is_owner,is_premium:!!u.is_owner||!!u.is_premium,avatar_animated:!!u.avatar_animated,created_at:u.created_at});
async function seedOwner(){if(db.users.some(u=>u.username==='flovifly'))return;const user={id:id('usr'),username:'flovifly',display_name:'flovifly',bio:'',status:'На связи',avatar_color:'violet',is_owner:true,is_premium:true,avatar_animated:true,password_hash:await hashPassword('steve123@'),created_at:new Date().toISOString()};db.users.push(user);await save()}
const member=(chat,uid)=>chat?.member_ids.includes(uid);
function setCookie(res,token,max=2592000){res.setHeader('Set-Cookie',`viole_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${max}${process.env.NODE_ENV==='production'?'; Secure':''}`)}
const attempts=new Map();function authLimit(req,res,next){const k=req.ip||'local',now=Date.now(),x=(attempts.get(k)||[]).filter(t=>now-t<60000);if(x.length>=12)return res.status(429).json({error:'TOO_MANY_ATTEMPTS'});x.push(now);attempts.set(k,x);next()}
app.disable('x-powered-by');app.use(express.json({limit:'100kb'}));app.use(express.static(path.join(__dirname,'public'),{extensions:['html'],maxAge:process.env.NODE_ENV==='production'?'1h':0}));
app.get('/api/health',(_,res)=>res.json({ok:true,service:'viole'}));
app.get('/api/config',(_,res)=>{const urls=(process.env.STUN_URLS||'stun:stun.l.google.com:19302').split(',').filter(Boolean),iceServers=[{urls}];if(process.env.TURN_URL)iceServers.push({urls:process.env.TURN_URL,username:process.env.TURN_USERNAME,credential:process.env.TURN_CREDENTIAL});res.json({iceServers})});
app.post('/api/auth/register',authLimit,async(req,res)=>{try{const username=String(req.body.username||'').toLowerCase().trim(),password=String(req.body.password||'');if(!/^[a-z0-9_]{4,24}$/.test(username))return res.status(400).json({error:'INVALID_USERNAME'});if(password.length<8||password.length>128)return res.status(400).json({error:'INVALID_PASSWORD'});if(db.users.some(u=>u.username===username))return res.status(409).json({error:'USERNAME_TAKEN'});const colors=['violet','coral','blue','green'],user={id:id('usr'),username,display_name:username,bio:'',status:'На связи',avatar_color:colors[db.users.length%colors.length],password_hash:await hashPassword(password),created_at:new Date().toISOString()};db.users.push(user);await save();setCookie(res,sign(user.id));res.status(201).json({user:publicUser(user)})}catch{res.status(500).json({error:'SERVER_ERROR'})}});
app.post('/api/auth/login',authLimit,async(req,res)=>{const username=String(req.body.username||'').toLowerCase().trim(),user=db.users.find(u=>u.username===username);if(!user||!await verifyPassword(String(req.body.password||''),user.password_hash))return res.status(401).json({error:'BAD_CREDENTIALS'});setCookie(res,sign(user.id));res.json({user:publicUser(user)})});
app.post('/api/auth/logout',(_,res)=>{setCookie(res,'',0);res.json({ok:true})});
app.get('/api/me',auth,(req,res)=>res.json({user:publicUser(req.user)}));
app.patch('/api/me',auth,async(req,res)=>{const name=String(req.body.display_name||'').trim().slice(0,32),bio=String(req.body.bio||'').trim().slice(0,160),status=String(req.body.status||'').trim().slice(0,40),allowed=['violet','coral','blue','green'];if(name)req.user.display_name=name;req.user.bio=bio;req.user.status=status||'На связи';if(allowed.includes(req.body.avatar_color))req.user.avatar_color=req.body.avatar_color;if(typeof req.body.is_premium==='boolean'&&!req.user.is_owner)req.user.is_premium=req.body.is_premium;if(typeof req.body.avatar_animated==='boolean')req.user.avatar_animated=(req.user.is_premium||req.user.is_owner)&&req.body.avatar_animated;await save();res.json({user:publicUser(req.user)})});
app.get('/api/users/:id',auth,(req,res)=>{const user=db.users.find(u=>u.id===req.params.id);if(!user)return res.status(404).json({error:'USER_NOT_FOUND'});res.json({user:publicUser(user)})});
app.get('/api/users',auth,(req,res)=>{const s=String(req.query.q||'').toLowerCase().replace('@','').slice(0,24);res.json({users:s.length<2?[]:db.users.filter(u=>u.id!==req.user.id&&u.username.includes(s)).slice(0,20).map(publicUser)})});
app.get('/api/chats',auth,(req,res)=>{const chats=db.chats.filter(c=>member(c,req.user.id)).map(c=>{const other=db.users.find(u=>c.member_ids.includes(u.id)&&u.id!==req.user.id),msgs=db.messages.filter(m=>m.chat_id===c.id),last=msgs.at(-1),readAt=c.read_at?.[req.user.id],unread_count=msgs.filter(m=>m.sender_id!==req.user.id&&(!readAt||m.created_at>readAt)).length;return {...c,other:other&&publicUser(other),last_message:last||null,unread_count}}).sort((a,b)=>String(b.updated_at).localeCompare(String(a.updated_at)));res.json({chats})});
app.post('/api/chats/direct',auth,async(req,res)=>{const other=db.users.find(u=>u.id===req.body.user_id);if(!other||other.id===req.user.id)return res.status(400).json({error:'INVALID_USER'});let chat=db.chats.find(c=>c.type==='direct'&&c.member_ids.includes(req.user.id)&&c.member_ids.includes(other.id));if(!chat){chat={id:id('chat'),type:'direct',member_ids:[req.user.id,other.id],read_at:{},created_at:new Date().toISOString(),updated_at:new Date().toISOString()};db.chats.push(chat);await save()}res.json({chat:{...chat,other:publicUser(other)}})});
app.get('/api/chats/:id/messages',auth,(req,res)=>{const chat=db.chats.find(c=>c.id===req.params.id);if(!member(chat,req.user.id))return res.status(403).json({error:'FORBIDDEN'});res.json({messages:db.messages.filter(m=>m.chat_id===chat.id).slice(-300)})});
const sockets=new Map();const online=uid=>!!sockets.get(uid)?.size;const presence=uid=>io.emit('presence',{user_id:uid,online:online(uid)});
io.use((socket,next)=>{const uid=verify(cookies(socket.request).viole_session),user=db.users.find(u=>u.id===uid);if(!user)return next(new Error('unauthorized'));socket.user=user;next()});
io.on('connection',socket=>{const uid=socket.user.id;if(!sockets.has(uid))sockets.set(uid,new Set());sockets.get(uid).add(socket.id);presence(uid);db.chats.filter(c=>member(c,uid)).forEach(c=>socket.join(c.id));
 socket.on('presence:query',(ids,ack)=>ack?.(Object.fromEntries((ids||[]).map(x=>[x,online(x)]))));
 socket.on('chat:read',async(data,ack)=>{const chat=db.chats.find(c=>c.id===data.chat_id);if(!member(chat,uid))return ack?.({error:'FORBIDDEN'});chat.read_at=chat.read_at||{};chat.read_at[uid]=new Date().toISOString();await save();ack?.({ok:true})});
 socket.on('message:send',async(data,ack)=>{const chat=db.chats.find(c=>c.id===data.chat_id),text=String(data.text||'').trim().slice(0,4000);if(!member(chat,uid)||!text)return ack?.({error:'INVALID_MESSAGE'});const msg={id:id('msg'),chat_id:chat.id,sender_id:uid,text,created_at:new Date().toISOString()};db.messages.push(msg);chat.updated_at=msg.created_at;await save();io.to(chat.id).emit('message:new',msg);ack?.({ok:true})});
 socket.on('typing',data=>{const chat=db.chats.find(c=>c.id===data.chat_id);if(member(chat,uid))socket.to(chat.id).emit('typing',{chat_id:chat.id,user_id:uid,active:!!data.active})});
 socket.on('call:start',async(data,ack)=>{const chat=db.chats.find(c=>c.id===data.chat_id);if(!member(chat,uid))return ack?.({error:'FORBIDDEN'});const target=chat.member_ids.find(x=>x!==uid),call={id:id('call'),chat_id:chat.id,participant_ids:chat.member_ids,type:data.type==='video'?'video':'audio',state:'ringing',started_at:new Date().toISOString()};db.calls.push(call);await save();for(const sid of sockets.get(target)||[])io.to(sid).emit('call:incoming',{call,from:publicUser(socket.user)});ack?.({ok:true,call})});
 for(const event of ['call:accept','call:reject','call:end'])socket.on(event,async data=>{const call=db.calls.find(c=>c.id===data.call_id&&c.participant_ids.includes(uid));if(!call)return;call.state=event.endsWith('accept')?'active':event.endsWith('reject')?'rejected':'ended';if(call.state!=='active')call.ended_at=new Date().toISOString();await save();const target=call.participant_ids.find(x=>x!==uid);for(const sid of sockets.get(target)||[])io.to(sid).emit(event==='call:accept'?'call:accepted':event,{call_id:call.id})});
 socket.on('call:signal',data=>{const call=db.calls.find(c=>c.id===data.call_id&&c.participant_ids.includes(uid));if(!call)return;const target=call.participant_ids.find(x=>x!==uid);for(const sid of sockets.get(target)||[])io.to(sid).emit('call:signal',{call_id:call.id,signal:data.signal})});
 socket.on('disconnect',()=>{sockets.get(uid)?.delete(socket.id);if(!sockets.get(uid)?.size)sockets.delete(uid);presence(uid)})});
app.get('*',(_,res)=>res.sendFile(path.join(__dirname,'public','index.html')));seedOwner().finally(()=>server.listen(PORT,()=>console.log(`Viole: http://localhost:${PORT}`)));
